import { Roboto } from "next/font/google";
import StoreProvider from "lib/StoreProvider";
import { ToggleThemeProvider } from "Context/ToggleMode";
import Nav from "components/Nav/Nav";
import ToasterHandlingMessage from "utils/ToasterHandlingMessage";
import ClientLayout from "./ClientLayout";
import "../globals.css";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Shopping Cart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <StoreProvider>
          <ToggleThemeProvider>
            <Nav />
            <ToasterHandlingMessage />
            <ClientLayout>{children}</ClientLayout>
          </ToggleThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
